const supabaseAuth = (() => {
  const root = "https://zttkujhoyuxerdewofkb.supabase.co";
  const key = "sb_publishable_lV9EA-XC2KQP5lBxr74puA_Zy1959R0";
  const sessionKey = "digihits-auth-session";
  let realtimeChannel, pendingRequests = 0, slowRequestTimer = 0;
  const setSlowRequest = (visible) => { const indicator = document.getElementById("network-progress"); if (indicator) indicator.hidden = !visible; };
  async function fetchWithTimeout(url, options) {
    const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 30000); pendingRequests += 1; if (pendingRequests === 1) slowRequestTimer = setTimeout(() => { if (pendingRequests && document.getElementById("app-dialog")?.hidden) setSlowRequest(true); }, 3000);
    try { return await fetch(url, { ...options, signal: controller.signal, cache: "no-store" }); }
    catch (error) { throw new Error(error.name === "AbortError" ? "Inloggningen tog för lång tid. Kontrollera nätet och försök igen." : "Kunde inte ansluta till servern. Kontrollera nätet och försök igen."); }
    finally { clearTimeout(timer); pendingRequests = Math.max(0, pendingRequests - 1); if (!pendingRequests) { clearTimeout(slowRequestTimer); setSlowRequest(false); } }
  }
  async function request(path, body, method = "POST", accessToken = key) {
    const response = await fetchWithTimeout(`${root}/auth/v1${path}`, { method, headers: { apikey: key, Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.msg || data.message || "Kunde inte kontakta kontotjänsten.");
    return data;
  }
  const tokenExpiresSoon = (token) => { try { return JSON.parse(atob(token.split(".")[1].replaceAll("-", "+").replaceAll("_", "/"))).exp * 1000 < Date.now() + 60000; } catch { return true; } };
  return {
    async signUp(name, email, password) { return request(`/signup?redirect_to=${encodeURIComponent(`${location.origin}${location.pathname}`)}`, { email, password, data: { display_name: name } }); },
    async signIn(email, password) { const data = await request("/token?grant_type=password", { email, password }); localStorage.setItem(sessionKey, JSON.stringify(data)); return data; },
    async refreshSession(force = false) { const session = this.session(); if (!session?.access_token) throw new Error("Logga in igen."); if (!force && !tokenExpiresSoon(session.access_token)) return session; if (!session.refresh_token) throw new Error("Logga in igen."); const refreshed = await request("/token?grant_type=refresh_token", { refresh_token: session.refresh_token }); const next = { ...session, ...refreshed, refresh_token: refreshed.refresh_token || session.refresh_token }; localStorage.setItem(sessionKey, JSON.stringify(next)); return next; },
    verify(email, password) { return request("/token?grant_type=password", { email, password }); },
    async playerNameTaken(name) { const response = await fetch(`${root}/rest/v1/rpc/digihits_player_name_taken`, { method: "POST", headers: { apikey: key, "Content-Type": "application/json" }, body: JSON.stringify({ requested_name: name.trim().toLocaleLowerCase("sv-SE") }) }); if (!response.ok) throw new Error("Kunde inte kontrollera spelarnamnet."); return response.json(); },
    requestPasswordReset(email) { return request(`/recover?redirect_to=${encodeURIComponent(`${location.origin}${location.pathname}?reset=1`)}`, { email }); },
    updatePassword(accessToken, password, currentPassword) { return request("/user", { password, ...(currentPassword ? { current_password: currentPassword } : {}) }, "PUT", accessToken); },
    async deleteAccount(confirmation) { const token = this.session()?.access_token; if (!token) throw new Error("Du är inte inloggad."); const response = await fetch(`${root}/functions/v1/delete-account`, { method: "POST", headers: { apikey: key, Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ confirmation }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Kunde inte radera kontot."); },
    async dataRequest(path, body, method = "GET") { const token = (await this.refreshSession()).access_token; const response = await fetchWithTimeout(`${root}/rest/v1/${path}`, { method, headers: { apikey: key, Authorization: `Bearer ${token}`, "Content-Type": "application/json", Prefer: "return=representation" }, ...(body ? { body: JSON.stringify(body) } : {}) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Kunde inte kontakta matchservern."); return data; },
    subscribeMatches(callback, messageCallback = callback) { if (!window.supabase || !this.session()?.access_token) return; if (realtimeChannel) realtimeChannel.unsubscribe(); const client = window.supabase.createClient(root, key, { auth: { persistSession: false } }); client.realtime.setAuth(this.session().access_token); realtimeChannel = client.channel("digihits-matches").on("postgres_changes", { event: "*", schema: "public", table: "online_matches" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "online_players" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "online_messages" }, messageCallback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_friend_requests" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_friendships" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_friend_notifications" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_match_invites" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_blocks" }, callback).on("postgres_changes", { event: "*", schema: "public", table: "digihits_match_join_requests" }, callback).on("postgres_changes", { event: "UPDATE", schema: "public", table: "digihits_profiles" }, callback).subscribe(); },
    unsubscribeMatches() { if (realtimeChannel) { realtimeChannel.unsubscribe(); realtimeChannel = null; } },
    session() { try { return JSON.parse(localStorage.getItem(sessionKey)); } catch { return null; } },
    async user(accessToken) { const response = await fetch(`${root}/auth/v1/user`, { headers: { apikey: key, Authorization: `Bearer ${accessToken}` } }); if (!response.ok && accessToken === this.session()?.access_token) { try { return await this.user((await this.refreshSession(true)).access_token); } catch (error) { if (response.status === 401 || response.status === 403) throw new Error("SESSION_EXPIRED"); throw error; } } if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? "SESSION_EXPIRED" : "Kunde inte läsa kontot."); return response.json(); },
    consumeVerification() { const values = new URLSearchParams(location.hash.slice(1)), access_token = values.get("access_token"); if (!access_token) return null; const session = { access_token, refresh_token: values.get("refresh_token") }; localStorage.setItem(sessionKey, JSON.stringify(session)); history.replaceState({}, "", `${location.pathname}${location.search}`); return { session, type: values.get("type") }; },
    signOut() { this.unsubscribeMatches(); localStorage.removeItem(sessionKey); }
  };
})();
